Dev
coding-sue-true/sparta-js-calculator pull request #1
Opened 2017-10-30 23:38 UTC by coding-sue-true

2017-10-31 10:00 UTC, JSChilds commented on index.html
> +    <!-- <script type="text/javascript" src="js/main.js"> </script> -->
You left this commented-out, so the calculator doesn't run!

2017-10-31 10:00 UTC, JSChilds commented on js/main.js
> +    };
You don't need semicolons after a }

2017-10-31 10:04 UTC, JSChilds requested changes
Code is really well layed-out and readable and it looks like it worked great, but the commented-out script tag means the calculator can't run. Keep an eye on these little details - it doesn't matter how great your code is if it doesn't run!

2017-11-05 10:27 UTC, coding-sue-true commented
Everything was now revised.

2017-11-06 09:48 UTC, JSChilds approved these changes

2017-11-06 09:48 UTC, merged